{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Side loading data inputs method 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/enhancers/smooth/core.py:21: NumbaExperimentalFeatureWarning: \u001b[1m\u001b[1m\u001b[1m\u001b[1mUse of isinstance() detected. This is an experimental feature.\u001b[0m\u001b[0m\u001b[0m\u001b[0m\n",
      "  v = np.where(Y > Z, a_, 1 - a_)\n",
      "/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/enhancers/smooth/core.py:128: NumbaExperimentalFeatureWarning: \u001b[1m\u001b[1m\u001b[1m\u001b[1mUse of isinstance() detected. This is an experimental feature.\u001b[0m\u001b[0m\u001b[0m\u001b[0m\n",
      "  Y_ = np.where(w == 0, 0, Y)\n"
     ]
    }
   ],
   "source": [
    "import pywapor\n",
    "import xarray as xr\n",
    "from functools import partial\n",
    "import pywapor.se_root as se_root\n",
    "\n",
    "et_look_config = pywapor.general.levels.pre_et_look_levels(level = \"level_1\")\n",
    "se_root_config = pywapor.general.levels.pre_se_root_levels(level = \"level_1\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Create a list of the meteorological variables."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# meteo_vars = ['t_air', 't_air_max', 't_air_min', 'u2m', 'v2m', 'qv', 'p_air', 'p_air_0', 'wv']\n",
    "meteo_vars = ['t_air_min']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'products': [{'source': 'GEOS5',\n",
       "   'product_name': 'inst3_2d_asm_Nx',\n",
       "   'enhancers': 'default'}],\n",
       " 'composite_type': 'min',\n",
       " 'temporal_interp': 'linear',\n",
       " 'spatial_interp': 'bilinear'}"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "et_look_config[\"t_air_min\"]"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We would have to convert the geotiff files to .cn format and locate them"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def meteo_sideload(**kwargs):\n",
    "    fh = r\"/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc\"\n",
    "    ds = xr.open_dataset(fh)\n",
    "    return ds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "meteo_config = [{\"source\": meteo_sideload, \"product_name\": \"SAWS_data\", \"enhancers\": []}]\n",
    "for var in meteo_vars:\n",
    "    et_look_config[var][\"products\"] = meteo_config\n",
    "    se_root_config[var][\"products\"] = meteo_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'products': [{'source': <function __main__.meteo_sideload(**kwargs)>,\n",
       "   'product_name': 'SAWS_data',\n",
       "   'enhancers': []}],\n",
       " 'composite_type': 'min',\n",
       " 'temporal_interp': 'linear',\n",
       " 'spatial_interp': 'bilinear'}"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "et_look_config[\"t_air_min\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'products': [{'source': functools.partial(<function se_root at 0x7f8c050c6660>, bin_length=1, sources='level_1'),\n",
       "   'product_name': 'v2',\n",
       "   'enhancers': 'default'}],\n",
       " 'composite_type': 'max',\n",
       " 'temporal_interp': None,\n",
       " 'spatial_interp': 'bilinear'}"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "et_look_config[\"se_root\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "se_root_dler = partial(se_root.se_root, sources = se_root_config)\n",
    "et_look_config[\"se_root\"][\"products\"][0][\"source\"] = se_root_dler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'products': [{'source': functools.partial(<function se_root at 0x7f8c050c6660>, sources={'ndvi': {'products': [{'source': 'MODIS', 'product_name': 'MOD13Q1.061', 'enhancers': 'default', 'is_example': True}, {'source': 'MODIS', 'product_name': 'MYD13Q1.061', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'nearest'}, 'lst': {'products': [{'source': 'MODIS', 'product_name': 'MOD11A1.061', 'enhancers': 'default'}, {'source': 'MODIS', 'product_name': 'MYD11A1.061', 'enhancers': 'default'}], 'temporal_interp': None, 'spatial_interp': 'nearest'}, 't_air': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 't_air_max': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 't_air_min': {'products': [{'source': <function meteo_sideload at 0x7f8c64156b60>, 'product_name': 'SAWS_data', 'enhancers': []}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'u2m': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'v2m': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'qv': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'wv': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'p_air': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'p_air_0': {'products': [{'source': 'GEOS5', 'product_name': 'inst3_2d_asm_Nx', 'enhancers': 'default'}], 'temporal_interp': 'linear', 'spatial_interp': 'bilinear'}, 'r0_bare': {'products': [{'source': 'STATICS', 'product_name': 'WaPOR2', 'enhancers': 'default'}], 'temporal_interp': None, 'spatial_interp': 'bilinear'}, 'r0_full': {'products': [{'source': 'STATICS', 'product_name': 'WaPOR2', 'enhancers': 'default'}], 'temporal_interp': None, 'spatial_interp': 'bilinear'}}),\n",
       "   'product_name': 'v2',\n",
       "   'enhancers': 'default'}],\n",
       " 'composite_type': 'max',\n",
       " 'temporal_interp': None,\n",
       " 'spatial_interp': 'bilinear'}"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "et_look_config[\"se_root\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "> PRE_ET_LOOK\n",
      "    --> Collecting `ndvi` from `MODIS.MOD13Q1.061`.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=76259ec004123e1c449bdc059e02be7e8688aa116a8fe05e3b0f2e9b41960ad4&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmpd1woxohc.nc, attempt 2 of 3 in 15 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=3c194e2b33aa77ae3be2e0ae88ed5855cdb506aed140c54575fb1f3e4445710e&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmpd1woxohc.nc, attempt 3 of 3 in 34 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=068611f7f7871b33fc512d3a9125bd0d75221fd6dc394546d59b896df9d0d300&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Collect attempt 1 of 2 for `MODIS.MOD13Q1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "        \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "    --> Collecting `ndvi` from `MODIS.MYD13Q1.061`.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=e97b4f02c59b2ce06a23af8d06afe449779516c82ea7ed7d0988d730a8664f61&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmpzavrzhnk.nc, attempt 2 of 3 in 15 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=fb3ac5b60c6fec91798d610878003923608214fde9ea5aa4716a6e406835801b&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmpzavrzhnk.nc, attempt 3 of 3 in 34 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=782cd1e1d7ffa36f92825e5c9e9e0ebb82dead5d6591493c43c991e226ffabf9&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Collect attempt 1 of 2 for `MODIS.MYD13Q1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "        \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "    --> Collecting `r0` from `MODIS.MCD43A3.061`.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=1a859243d227dbec59b7287ffa5c8afd50a8c2c8230058a83d38920454a5bc6d&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTUNENDNBMy4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmphrvrdgns.nc, attempt 2 of 3 in 15 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=ef1f887efc7adad760e41fd62a342211759ea506c4a68b05bbd54ce7a82a88fa&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTUNENDNBMy4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmphrvrdgns.nc, attempt 3 of 3 in 34 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=4818a074cc9862d5f3a2cdd77e31c57cc537225d0fd4eb356490cdcb68cab154&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTUNENDNBMy4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Collect attempt 1 of 2 for `MODIS.MCD43A3.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MCD43A3.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "        \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MCD43A3.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "    --> Collecting `p` from `CHIRPS.P05`.\n",
      "        --> Saving merged data.         \n",
      "            > peak-memory-usage: 353.0KB, execution-time: 0:00:03.141175.\n",
      "            > chunksize|dimsize: [time: 17|17, y: 16|16, x: 16|16]\n",
      "            > timesize: 17 [2019-12-29T00:30, ..., 2020-01-14T00:30]\n",
      "    --> Collecting `z` from `SRTM.30M`.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=b1d48855195d8fd3c1fb41d3faadc0f9499b37f6bc2aa1b7f13cd5b21cc2311b&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvU1JUTUdMMV9OQy4wMDMvUzM0RTAxOC5TUlRNR0wxX05DLm5jbWwubmM0P2xvbiUyQ2xhdCUyQ3RpbWU [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmpqilo8ris.nc, attempt 2 of 3 in 15 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=ac0b2edf503ca0e86504adc50f8e0b962c2ee4a4958cb731fb8190b8a5cb540c&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvU1JUTUdMMV9OQy4wMDMvUzM0RTAxOC5TUlRNR0wxX05DLm5jbWwubmM0P2xvbiUyQ2xhdCUyQ3RpbWU [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Trying to download /tmp/tmpqilo8ris.nc, attempt 3 of 3 in 34 seconds.\n",
      "        --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=a83caf3b754ff5a2a796f834bb37d9333b2ac036212c6b6e9af3e91c53ee1b7a&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvU1JUTUdMMV9OQy4wMDMvUzM0RTAxOC5TUlRNR0wxX05DLm5jbWwubmM0P2xvbiUyQ2xhdCUyQ3RpbWU [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "        --> Collect attempt 1 of 2 for `SRTM.30M` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/SRTMGL1_NC.003/S34E018.SRTMGL1_NC.ncml.nc4?lon%2Clat%2Ctime after 3 attempts.).\n",
      "        \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/SRTM.py\", line 216, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/SRTMGL1_NC.003/S34E018.SRTMGL1_NC.ncml.nc4?lon%2Clat%2Ctime after 3 attempts.\n",
      "    --> Collecting `ra` from `MERRA2.M2T1NXRAD.5.12.4`.\n",
      "        --> Saving merged data.                               \n",
      "            > peak-memory-usage: 87.6KB, execution-time: 0:00:02.075374.\n",
      "            > chunksize|dimsize: [time: 408|408, y: 4|4, x: 4|4]\n",
      "            > timesize: 408 [2019-12-29T01:00, ..., 2020-01-15T00:00]\n",
      "    --> Collecting `t_air`, `t_air_max`, `u2m`, `v2m`, `qv`, `p_air`, `p_air_0`, `wv` from `GEOS5.inst3_2d_asm_Nx`.\n",
      "        --> Downloading data.\n",
      "            > peak-memory-usage: 969.1KB, execution-time: 0:00:48.203722.\n",
      "            > chunksize|dimsize: [time: 129|129, y: 5|5, x: 5|5]\n",
      "        --> Applying 'kelvin_to_celsius' to `t_air`.\n",
      "        --> Applying 'kelvin_to_celsius' to `t_air_max`.\n",
      "        --> Applying 'pa_to_kpa' to `p_air`.\n",
      "        --> Applying 'pa_to_kpa' to `p_air_0`.\n",
      "        --> Saving netCDF.\n",
      "            > peak-memory-usage: 1.6MB, execution-time: 0:00:02.266253.\n",
      "            > chunksize|dimsize: [time: 129|129, y: 5|5, x: 5|5]\n",
      "            > timesize: 129 [2019-12-29T01:30, ..., 2020-01-14T01:30]\n",
      "    --> Collecting `t_air_min` from `meteo_sideload.SAWS_data`.\n",
      "        --> Collect attempt 1 of 2 for `meteo_sideload.SAWS_data` failed, giving up now, see full traceback below for more info. (FileNotFoundError: [Errno 2] No such file or directory: b'/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc').\n",
      "        \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/file_manager.py\", line 210, in _acquire_with_cache_info\n",
      "    file = self._cache[self._key]\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/lru_cache.py\", line 56, in __getitem__\n",
      "    value = self._cache[key]\n",
      "            ~~~~~~~~~~~^^^^^\n",
      "KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '96161fe2-bf7a-4d35-8fc7-06335a0d7098']\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/tmp/ipykernel_1873/2831094351.py\", line 3, in meteo_sideload\n",
      "    ds = xr.open_dataset(fh)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/api.py\", line 566, in open_dataset\n",
      "    backend_ds = backend.open_dataset(\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 588, in open_dataset\n",
      "    store = NetCDF4DataStore.open(\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 389, in open\n",
      "    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 336, in __init__\n",
      "    self.format = self.ds.data_model\n",
      "                  ^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 398, in ds\n",
      "    return self._acquire()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 392, in _acquire\n",
      "    with self._manager.acquire_context(needs_lock) as root:\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/contextlib.py\", line 137, in __enter__\n",
      "    return next(self.gen)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/file_manager.py\", line 198, in acquire_context\n",
      "    file, cached = self._acquire_with_cache_info(needs_lock)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/file_manager.py\", line 216, in _acquire_with_cache_info\n",
      "    file = self._opener(*self._args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"src/netCDF4/_netCDF4.pyx\", line 2307, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"src/netCDF4/_netCDF4.pyx\", line 1925, in netCDF4._netCDF4._ensure_nc_success\n",
      "FileNotFoundError: [Errno 2] No such file or directory: b'/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc'\n",
      "    --> Collecting `land_mask`, `rs_min`, `z_obst_max` from `GLOBCOVER.2009_V2.3_Global`.\n",
      "        --> Calculating `land_mask` from `lulc`.\n",
      "        --> Calculating `rs_min` from `lulc`.\n",
      "        --> Calculating `z_obst_max` from `lulc`.\n",
      "        --> Saving 2009_V2.3_Global.nc.\n",
      "            > peak-memory-usage: 2.9MB, execution-time: 0:00:02.202856.\n",
      "            > chunksize|dimsize: [y: 252|252, x: 247|247]\n",
      "    --> Collecting `lw_offset`, `lw_slope`, `z_oro`, `rn_offset`, `rn_slope`, `t_amp_year`, `t_opt`, `vpd_slope` from `STATICS.WaPOR2`.\n",
      "        --> Saving WaPOR2.nc.\n",
      "            > peak-memory-usage: 7.4MB, execution-time: 0:00:02.267319.\n",
      "            > chunksize|dimsize: [y: 350|350, x: 344|344]\n",
      "    --> Collecting `se_root` from `se_root.v2`.\n",
      "        --> Using se_root v2.\n",
      "        > PRE_SE_ROOT\n",
      "            --> Collecting `lst` from `MODIS.MOD11A1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=cb998d2fcd8111b8d6bda93885e024933245fc17b3401cf71ac340a56074f7a2&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmp8v7mvxqs.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=043ee90c900db65cf9bbd682193dffa283eec7d490d585ceb9f2af62fb8ab3e1&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmp8v7mvxqs.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=7a1ac63fcc90121a85e0d18a4bb01ee0c767a9684dcf0c232cb062587b9aa4c5&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 1 of 2 for `MODIS.MOD11A1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Collecting `lst` from `MODIS.MYD11A1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=0d3824cec815ae14b7c7d239a0c1700f6bb6524e87222b48dd488c5b7e240d3f&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmptej8qqt3.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=59cd645422adb7393f46b8bf8c10ab0b0b3f98f0f434b4e9065ecc3e8dfcb49a&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmptej8qqt3.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=b2f93737a7b2062c40bdee03712989cc983b7136099b615e14d6c16d728255af&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 1 of 2 for `MODIS.MYD11A1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Collecting `lst` from `MODIS.MOD11A1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=d1f7ad685490e4c4c7d3c5f4b70fbe3413bd19ee72c318e652f1a33499db8942&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmppl2l1c5w.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=bf4f6632d8401064de8e2a24784108fb10acc96c546958576cf55ebcb479e84a&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmppl2l1c5w.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=42e3d9c6f326f27caa1c819ba4142b6c8787823dd0800ab072c10136af8fa81d&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 2 of 2 for `MODIS.MOD11A1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Collecting `lst` from `MODIS.MYD11A1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=cbbe1914497fafac6a78b8c60195a260f1c2c5bf2d8c08f2a0a206a3f0d1a040&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmplvn2xh4s.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=ea1893058f5ae675147aa2cfe3f49d61fd7ff3f6456de3ad71945e0a791bd5bb&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmplvn2xh4s.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=0b6243bebfe9bc22ed6e3214834b3c76236f6ebdc36437ff870ea2795fce4453&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTFBMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 2 of 2 for `MODIS.MYD11A1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD11A1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Continuing run without `lst` from `MOD11A1.061`.\n",
      "            --> Continuing run without `lst` from `MYD11A1.061`.\n",
      "            --> Continuing run without `lst`, couldn't collect any product.\n",
      "            --> Collecting `ndvi` from `MODIS.MOD13Q1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=673d743acbeda810726252b6f343f07110b03026d64fb47a3d54085e9e8436e0&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmpl_o743yr.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=c785ea265934b8e5ad1942b91a92c74242363ac1c574b75d2f7f6259cf028f92&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmpl_o743yr.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=8511d58b96de7c6863b3606515b99ccec0796ed9cfc86582b7bfa91742eca3fb&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 1 of 2 for `MODIS.MOD13Q1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Collecting `ndvi` from `MODIS.MYD13Q1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=1375760ca54a5950937a963bc16d6c798fcf62fa1a22d3fc3b8b3a7ab3694eb3&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmp79gc5u5p.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=c8022d7084d2502049dcd862582e1c36e3b8dc02b2eaa4551dd253bc8939d8e3&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmp79gc5u5p.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=c57bea8ef76a9aa6701f7a04806889f3064b34cd6bdcceabece922c0c51885ec&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 1 of 2 for `MODIS.MYD13Q1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MYD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Collecting `t_air`, `t_air_max`, `u2m`, `v2m`, `qv`, `wv`, `p_air`, `p_air_0` from `GEOS5.inst3_2d_asm_Nx`.\n",
      "                    > timesize: 129 [2019-12-29T01:30, ..., 2020-01-14T01:30]\n",
      "            --> Collecting `t_air_min` from `meteo_sideload.SAWS_data`.\n",
      "                --> Collect attempt 1 of 2 for `meteo_sideload.SAWS_data` failed, giving up now, see full traceback below for more info. (FileNotFoundError: [Errno 2] No such file or directory: b'/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc').\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/file_manager.py\", line 210, in _acquire_with_cache_info\n",
      "    file = self._cache[self._key]\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/lru_cache.py\", line 56, in __getitem__\n",
      "    value = self._cache[key]\n",
      "            ~~~~~~~~~~~^^^^^\n",
      "KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '3f9ab77b-1dfe-45cd-875a-41fd578e324a']\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/tmp/ipykernel_1873/2831094351.py\", line 3, in meteo_sideload\n",
      "    ds = xr.open_dataset(fh)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/api.py\", line 566, in open_dataset\n",
      "    backend_ds = backend.open_dataset(\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 588, in open_dataset\n",
      "    store = NetCDF4DataStore.open(\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 389, in open\n",
      "    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 336, in __init__\n",
      "    self.format = self.ds.data_model\n",
      "                  ^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 398, in ds\n",
      "    return self._acquire()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/netCDF4_.py\", line 392, in _acquire\n",
      "    with self._manager.acquire_context(needs_lock) as root:\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/contextlib.py\", line 137, in __enter__\n",
      "    return next(self.gen)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/file_manager.py\", line 198, in acquire_context\n",
      "    file, cached = self._acquire_with_cache_info(needs_lock)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/xarray/backends/file_manager.py\", line 216, in _acquire_with_cache_info\n",
      "    file = self._opener(*self._args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"src/netCDF4/_netCDF4.pyx\", line 2307, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"src/netCDF4/_netCDF4.pyx\", line 1925, in netCDF4._netCDF4._ensure_nc_success\n",
      "FileNotFoundError: [Errno 2] No such file or directory: b'/workspaces/GIT716.ET/NetCDF_files/airTemp_min.nc'\n",
      "            --> Collecting `r0_bare`, `r0_full` from `STATICS.WaPOR2`.\n",
      "                --> Saving WaPOR2.nc.\n",
      "                    --> Appending data to an existing file.\n",
      "                    > peak-memory-usage: 4.5MB, execution-time: 0:00:02.141477.\n",
      "                    > chunksize|dimsize: [y: 350|350, x: 344|344]\n",
      "            --> Collecting `ndvi` from `MODIS.MOD13Q1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=b31333773cd24be03c2d7332a61f4c554ac950d68841d1d6c342ac99a8f9eef5&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmp5rg8nkau.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=30b10b60a1c34a3d4a9a31aa6af90625694fcf413c19ae88f1fda13e5cd5d44d&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmp5rg8nkau.nc, attempt 3 of 3 in 34 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=331978b06512509adcbc5cbb28894059e4419c93f85cbe5c5115e83a37de7b81&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTU9EMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Collect attempt 2 of 2 for `MODIS.MOD13Q1.061` failed, giving up now, see full traceback below for more info. (NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.).\n",
      "                \n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py\", line 89, in collect_sources\n",
      "    x = dler(**args)\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py\", line 383, in download\n",
      "    ds = opendap.download(fn, product_name, coords,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in download\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 68, in <listcomp>\n",
      "    idxss = [find_idxs(url_func(product_name, x), selection, session) for x in tiles]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py\", line 126, in find_idxs\n",
      "    fp = download_url(url_coords, fp, session, waitbar = False, verify = verify)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py\", line 315, in download_url\n",
      "    raise NameError(f\"Could not download {url} after {max_tries} attempts.\")\n",
      "NameError: Could not download https://opendap.cr.usgs.gov/opendap/hyrax/MOD13Q1.061/h19v12.ncml.nc4?XDim%2CYDim%2Ctime after 3 attempts.\n",
      "            --> Collecting `ndvi` from `MODIS.MYD13Q1.061`.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=86582ba282c68cf731801caa06619dbc5dec37db7d940e790e4c1eeddd315f75&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmptdv25zlz.nc, attempt 2 of 3 in 15 seconds.\n",
      "                --> Server error 500 Server Error: Internal Server Error for url: https://opendap.cr.usgs.gov/opendap/hyrax/oauth2?code=010920c9ecea9715b0ef1f24c80cfcb6e74b410f44244380a38f3a91947215f1&state=aHR0cHM6Ly9vcGVuZGFwLmNyLnVzZ3MuZ292L29wZW5kYXAvaHlyYXgvTVlEMTNRMS4wNjEvaDE5djEyLm5jbWwubmM0P1hEaW0lMkNZRGltJTJDdGltZQ [<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n",
      "<html><head>\n",
      "<title>500 Internal Server Error</title>\n",
      "</head><body>\n",
      "<h1>Internal Server Error</h1>\n",
      "<p>The server encountered an internal error or\n",
      "misconfiguration and was unable to complete\n",
      "your request.</p>\n",
      "<p>Please contact the server administrator at \n",
      " root@localhost to inform them of the time this error occurred,\n",
      " and the actions you performed just before this error.</p>\n",
      "<p>More information about this error may be available\n",
      "in the server error log.</p>\n",
      "</body></html>\n",
      "].\n",
      "                --> Trying to download /tmp/tmptdv25zlz.nc, attempt 3 of 3 in 34 seconds.\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[11], line 5\u001b[0m\n\u001b[1;32m      3\u001b[0m latlim \u001b[39m=\u001b[39m [\u001b[39m-\u001b[39m\u001b[39m34.050015\u001b[39m, \u001b[39m-\u001b[39m\u001b[39m33.369369\u001b[39m]\n\u001b[1;32m      4\u001b[0m lonlim \u001b[39m=\u001b[39m [\u001b[39m18.723629\u001b[39m, \u001b[39m19.390929\u001b[39m]\n\u001b[0;32m----> 5\u001b[0m input_ds \u001b[39m=\u001b[39m pywapor\u001b[39m.\u001b[39;49mpre_et_look\u001b[39m.\u001b[39;49mmain(folder, latlim, lonlim, timelim, sources \u001b[39m=\u001b[39;49m et_look_config)\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/pre_et_look.py:154\u001b[0m, in \u001b[0;36mmain\u001b[0;34m(folder, latlim, lonlim, timelim, sources, bin_length, enhancers)\u001b[0m\n\u001b[1;32m    150\u001b[0m adjusted_timelim \u001b[39m=\u001b[39m [bins[\u001b[39m0\u001b[39m], bins[\u001b[39m-\u001b[39m\u001b[39m1\u001b[39m]]\n\u001b[1;32m    151\u001b[0m buffered_timelim \u001b[39m=\u001b[39m [adjusted_timelim[\u001b[39m0\u001b[39m] \u001b[39m-\u001b[39m np\u001b[39m.\u001b[39mtimedelta64(\u001b[39m3\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39mD\u001b[39m\u001b[39m\"\u001b[39m), \n\u001b[1;32m    152\u001b[0m                     adjusted_timelim[\u001b[39m1\u001b[39m] \u001b[39m+\u001b[39m np\u001b[39m.\u001b[39mtimedelta64(\u001b[39m3\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39mD\u001b[39m\u001b[39m\"\u001b[39m)]\n\u001b[0;32m--> 154\u001b[0m dss, sources \u001b[39m=\u001b[39m downloader\u001b[39m.\u001b[39;49mcollect_sources(folder, sources, latlim, lonlim, buffered_timelim)\n\u001b[1;32m    156\u001b[0m ds \u001b[39m=\u001b[39m compositer\u001b[39m.\u001b[39mmain(dss, sources, folder, general_enhancers, bins)\n\u001b[1;32m    158\u001b[0m t2 \u001b[39m=\u001b[39m datetime\u001b[39m.\u001b[39mdatetime\u001b[39m.\u001b[39mnow()\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py:89\u001b[0m, in \u001b[0;36mcollect_sources\u001b[0;34m(folder, sources, latlim, lonlim, timelim, landsat_order_only)\u001b[0m\n\u001b[1;32m     86\u001b[0m     args\u001b[39m.\u001b[39mupdate({\u001b[39m\"\u001b[39m\u001b[39mmax_attempts\u001b[39m\u001b[39m\"\u001b[39m: \u001b[39m1\u001b[39m})\n\u001b[1;32m     88\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> 89\u001b[0m     x \u001b[39m=\u001b[39m dler(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49margs)\n\u001b[1;32m     90\u001b[0m     attempts[(source, product_name)] \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m max_attempts \u001b[39m*\u001b[39m \u001b[39m10\u001b[39m\n\u001b[1;32m     91\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/se_root.py:52\u001b[0m, in \u001b[0;36mse_root\u001b[0;34m(folder, latlim, lonlim, timelim, sources, bin_length, se_root_version, **kwargs)\u001b[0m\n\u001b[1;32m     49\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(sources, \u001b[39mstr\u001b[39m):\n\u001b[1;32m     50\u001b[0m     sources \u001b[39m=\u001b[39m levels\u001b[39m.\u001b[39mpre_se_root_levels(sources)\n\u001b[0;32m---> 52\u001b[0m ds_in \u001b[39m=\u001b[39m pre_se_root\u001b[39m.\u001b[39;49mmain(folder, latlim, lonlim, timelim, sources, bin_length, buffer_timelim \u001b[39m=\u001b[39;49m \u001b[39mFalse\u001b[39;49;00m)\n\u001b[1;32m     53\u001b[0m ds_out \u001b[39m=\u001b[39m main(ds_in, se_root_version \u001b[39m=\u001b[39m se_root_version)\n\u001b[1;32m     55\u001b[0m \u001b[39mreturn\u001b[39;00m ds_out\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/pre_se_root.py:131\u001b[0m, in \u001b[0;36mmain\u001b[0;34m(folder, latlim, lonlim, timelim, sources, bin_length, enhancers, buffer_timelim, **kwargs)\u001b[0m\n\u001b[1;32m    128\u001b[0m     buffered_timelim \u001b[39m=\u001b[39m timelim\n\u001b[1;32m    130\u001b[0m example_dss, example_sources \u001b[39m=\u001b[39m downloader\u001b[39m.\u001b[39mcollect_sources(folder, example_sources, latlim, lonlim, adjusted_timelim, landsat_order_only \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m)\n\u001b[0;32m--> 131\u001b[0m other_dss, other_sources \u001b[39m=\u001b[39m downloader\u001b[39m.\u001b[39;49mcollect_sources(folder, other_sources, latlim, lonlim, buffered_timelim)\n\u001b[1;32m    133\u001b[0m \u001b[39m# If there are example-t variables that rely on landsat, try one more time to collect them.\u001b[39;00m\n\u001b[1;32m    134\u001b[0m \u001b[39mif\u001b[39;00m np\u001b[39m.\u001b[39many(\u001b[39mlist\u001b[39m({var: np\u001b[39m.\u001b[39many([product_info[\u001b[39m\"\u001b[39m\u001b[39msource\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m==\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mLANDSAT\u001b[39m\u001b[39m\"\u001b[39m \u001b[39mfor\u001b[39;00m product_info \u001b[39min\u001b[39;00m info[\u001b[39m\"\u001b[39m\u001b[39mproducts\u001b[39m\u001b[39m\"\u001b[39m]]) \u001b[39mfor\u001b[39;00m var, info \u001b[39min\u001b[39;00m example_sources\u001b[39m.\u001b[39mitems()}\u001b[39m.\u001b[39mvalues())):\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/downloader.py:89\u001b[0m, in \u001b[0;36mcollect_sources\u001b[0;34m(folder, sources, latlim, lonlim, timelim, landsat_order_only)\u001b[0m\n\u001b[1;32m     86\u001b[0m     args\u001b[39m.\u001b[39mupdate({\u001b[39m\"\u001b[39m\u001b[39mmax_attempts\u001b[39m\u001b[39m\"\u001b[39m: \u001b[39m1\u001b[39m})\n\u001b[1;32m     88\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> 89\u001b[0m     x \u001b[39m=\u001b[39m dler(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49margs)\n\u001b[1;32m     90\u001b[0m     attempts[(source, product_name)] \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m max_attempts \u001b[39m*\u001b[39m \u001b[39m10\u001b[39m\n\u001b[1;32m     91\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/product/MODIS.py:383\u001b[0m, in \u001b[0;36mdownload\u001b[0;34m(folder, latlim, lonlim, timelim, product_name, req_vars, variables, post_processors)\u001b[0m\n\u001b[1;32m    381\u001b[0m un_pw \u001b[39m=\u001b[39m accounts\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39mNASA\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    382\u001b[0m request_dims \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m--> 383\u001b[0m ds \u001b[39m=\u001b[39m opendap\u001b[39m.\u001b[39;49mdownload(fn, product_name, coords, \n\u001b[1;32m    384\u001b[0m             variables, post_processors, fn_func, url_func, un_pw \u001b[39m=\u001b[39;49m un_pw, \n\u001b[1;32m    385\u001b[0m             tiles \u001b[39m=\u001b[39;49m tiles, data_source_crs \u001b[39m=\u001b[39;49m data_source_crs, parallel \u001b[39m=\u001b[39;49m parallel, \n\u001b[1;32m    386\u001b[0m             spatial_tiles \u001b[39m=\u001b[39;49m spatial_tiles, request_dims \u001b[39m=\u001b[39;49m request_dims,\n\u001b[1;32m    387\u001b[0m             timedelta \u001b[39m=\u001b[39;49m timedelta)\n\u001b[1;32m    389\u001b[0m \u001b[39mreturn\u001b[39;00m ds[req_vars_orig]\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py:68\u001b[0m, in \u001b[0;36mdownload\u001b[0;34m(fp, product_name, coords, variables, post_processors, fn_func, url_func, un_pw, tiles, data_source_crs, parallel, spatial_tiles, request_dims, timedelta)\u001b[0m\n\u001b[1;32m     66\u001b[0m session \u001b[39m=\u001b[39m start_session(url_func(product_name, tiles[\u001b[39m0\u001b[39m]), selection, un_pw)\n\u001b[1;32m     67\u001b[0m \u001b[39mif\u001b[39;00m spatial_tiles:\n\u001b[0;32m---> 68\u001b[0m     idxss \u001b[39m=\u001b[39m [find_idxs(url_func(product_name, x), selection, session) \u001b[39mfor\u001b[39;49;00m x \u001b[39min\u001b[39;49;00m tiles]\n\u001b[1;32m     69\u001b[0m     urls \u001b[39m=\u001b[39m [create_url(url_func(product_name, x), idxs, variables, request_dims \u001b[39m=\u001b[39m request_dims) \u001b[39mfor\u001b[39;00m x, idxs \u001b[39min\u001b[39;00m \u001b[39mzip\u001b[39m(tiles, idxss)]\n\u001b[1;32m     70\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py:68\u001b[0m, in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m     66\u001b[0m session \u001b[39m=\u001b[39m start_session(url_func(product_name, tiles[\u001b[39m0\u001b[39m]), selection, un_pw)\n\u001b[1;32m     67\u001b[0m \u001b[39mif\u001b[39;00m spatial_tiles:\n\u001b[0;32m---> 68\u001b[0m     idxss \u001b[39m=\u001b[39m [find_idxs(url_func(product_name, x), selection, session) \u001b[39mfor\u001b[39;00m x \u001b[39min\u001b[39;00m tiles]\n\u001b[1;32m     69\u001b[0m     urls \u001b[39m=\u001b[39m [create_url(url_func(product_name, x), idxs, variables, request_dims \u001b[39m=\u001b[39m request_dims) \u001b[39mfor\u001b[39;00m x, idxs \u001b[39min\u001b[39;00m \u001b[39mzip\u001b[39m(tiles, idxss)]\n\u001b[1;32m     70\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/opendap.py:126\u001b[0m, in \u001b[0;36mfind_idxs\u001b[0;34m(base_url, selection, session, verify)\u001b[0m\n\u001b[1;32m    124\u001b[0m fp \u001b[39m=\u001b[39m tempfile\u001b[39m.\u001b[39mNamedTemporaryFile(suffix\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.nc\u001b[39m\u001b[39m\"\u001b[39m)\u001b[39m.\u001b[39mname\n\u001b[1;32m    125\u001b[0m url_coords \u001b[39m=\u001b[39m base_url \u001b[39m+\u001b[39m urllib\u001b[39m.\u001b[39mparse\u001b[39m.\u001b[39mquote(\u001b[39m\"\u001b[39m\u001b[39m,\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mjoin(selection\u001b[39m.\u001b[39mkeys()))\n\u001b[0;32m--> 126\u001b[0m fp \u001b[39m=\u001b[39m download_url(url_coords, fp, session, waitbar \u001b[39m=\u001b[39;49m \u001b[39mFalse\u001b[39;49;00m, verify \u001b[39m=\u001b[39;49m verify)\n\u001b[1;32m    127\u001b[0m ds \u001b[39m=\u001b[39m xr\u001b[39m.\u001b[39mopen_dataset(fp, decode_coords \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mall\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    128\u001b[0m idxs \u001b[39m=\u001b[39m {k: _find_idxs(ds, k, v) \u001b[39mfor\u001b[39;00m k, v \u001b[39min\u001b[39;00m selection\u001b[39m.\u001b[39mitems()}\n",
      "File \u001b[0;32m/opt/conda/envs/pywapor/lib/python3.11/site-packages/pywapor/collect/protocol/crawler.py:300\u001b[0m, in \u001b[0;36mdownload_url\u001b[0;34m(url, fp, session, waitbar, headers, max_tries, wait_sec, verify)\u001b[0m\n\u001b[1;32m    298\u001b[0m     waiter \u001b[39m=\u001b[39m \u001b[39mint\u001b[39m((try_n\u001b[39m*\u001b[39m\u001b[39m*\u001b[39m\u001b[39m1.2\u001b[39m) \u001b[39m*\u001b[39m wait_sec)\n\u001b[1;32m    299\u001b[0m     log\u001b[39m.\u001b[39minfo(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m--> Trying to download \u001b[39m\u001b[39m{\u001b[39;00mfp\u001b[39m}\u001b[39;00m\u001b[39m, attempt \u001b[39m\u001b[39m{\u001b[39;00mtry_n\u001b[39m+\u001b[39m\u001b[39m1\u001b[39m\u001b[39m}\u001b[39;00m\u001b[39m of \u001b[39m\u001b[39m{\u001b[39;00mmax_tries\u001b[39m}\u001b[39;00m\u001b[39m in \u001b[39m\u001b[39m{\u001b[39;00mwaiter\u001b[39m}\u001b[39;00m\u001b[39m seconds.\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> 300\u001b[0m     time\u001b[39m.\u001b[39msleep(waiter)\n\u001b[1;32m    301\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    302\u001b[0m     fp \u001b[39m=\u001b[39m _download_url(url, fp, session \u001b[39m=\u001b[39m session, waitbar \u001b[39m=\u001b[39m waitbar, headers \u001b[39m=\u001b[39m headers, verify \u001b[39m=\u001b[39m verify)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "folder = r\"/workspaces/GIT716.ET/Results_level2\"\n",
    "timelim = [\"2020-01-01\", \"2020-01-10\"]\n",
    "latlim = [-34.050015, -33.369369]\n",
    "lonlim = [18.723629, 19.390929]\n",
    "input_ds = pywapor.pre_et_look.main(folder, latlim, lonlim, timelim, sources = et_look_config)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pywapor",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
